
server.port=8083

spring.data.mongodb.uri=mongodb://localhost:27017/fitnessmicroactivity

# Eureka client configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092


# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka topic configuration
kafka.topic.name=activity-events

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
